### ISSUE TITLE
[ROADMAP] V7

### ISSUE THREAD

**Issue by Romakita** [TypedProject/ts-express-decorators#1503]
## Stories

- [x] Use virtual router instead of native Express/Koa router (PR: #1987)
- [x] Remove possibility to register twice method with the same path + http verb (PR: #2006)
- [x] Remove componentsScan options and any globpattern to discover services
- [x] Support async_hook directly in @tsed/di. (PR: #1860)
- [x] OIDC: use /oidc basePath by default instead (Related: #1490, PR: https://github.com/tsedio/tsed/pull/1863)
- [x] Switch on ESM (already supported in v6 [https://github.com/tsedio/tsed/releases/tag/v6.102.8](https://github.com/tsedio/tsed/releases/tag/v6.102.8))
- [x] Remove export @tsed/platform-cache from @tsed/common PlatformCache (#1657)
- [x] Add body parser on each endpoint directly (already supported in v6)
- [x] Use [@tsed/engines](https://tsed.io/docs/templating.html#use-tsed-engines)
- [x] Remove ConverterService
- [x] Remove deprecated methods from v6

### Removed

- [x] ~Lazyloading Http and Https server (#1654)~ (not necessary with: https://github.com/tsedio/tsed/pull/1662)
- [x] ~Remove openspec 2 support~ (#1756 will use plugin to convert OS3 to OS2)
- [x] ~DI: injector.invoke() will be async to allow async dep in async factory~ #1502 (implemented in v6, #1541)

## Why removing componentsScan and globpattern support

ComponentsScan is an option to import services using a globpattern. It's pretty usefull when you start new application.
But this option can cause some issues or misunderstood:

- When you change a location for a Controller/Service/Modules, the code isn't discovered as expected. It's normal, the server have default configuration like `**/services/**/*.ts`. if the code is outside of this pattern, the won't be loaded.
- Performance issue. The global pattern have a huge impact on the server bootstrap!
- Isn't compatible with Webpack or any bundler because the code imported dynamically.
- Importing dynamically code using glob pattern in production may be a breach exploitable by hackers to inject code.

This is why I decided to replace the componentsScan by another tools named `barrelsby`. The latest CLI version install barrelsby on fresh project. This tool use globpattern to generate an index files (barrel file) with all controllers. This tool isn't invoked a the runtime but before when you build the code or you invoke the NPM script to generates barrels.

It's maybe less magical, but it resolve all previous described issues encountered with the componentsScan. 

You can try this tool by generate a project with `tsed init .`. In the new project you'll have a new NPM task `barrels`
to generate barrels files. You can customize easily the barrelsby configuration to generate multiple barrels file at different levels of your project!

Here is the main points about barrelsby usage in a Ts.ED project:
```json
{
   "scripts": {
      "build": "yarn run barrels && yarn run tsc --project tsconfig.compile.json",
      "barrels": "barrelsby --config .barrelsby.json",
      "start": "yarn run barrels && tsnd --inspect --ignore-watch node_modules --respawn --transpile-only -r tsconfig-paths/register src/index.ts"
   }
}
```

**.barrelsby.json**
```json
{
  "directory": [
    "./src/controllers/rest"
  ],
  "exclude": [
    "__mock__",
    "__mocks__",
    ".spec.ts"
  ],
  "delete": true
}
```

This configuration generate index.ts file with the following contents:

```typescript
/**
 * @file Automatically generated by barrelsby.
 */

export * from "./HelloWorldController";
export * from "./UserController";
```

And we can use it as following:

```typescript
import * as rest from "./controllers/rest";

@Configuration({
  mount: {
    "/rest": [
      ...Object.values(rest)
    ]
  }
})
```

#### Keep the componentsScan

The support usage will be removed from the server configuration, but you can use the `@tsed/components-scan` to load your code dynamicly! 

Here is the right way to use the componentsScan since v6.104.0:

```typescript
import {$log} from "@tsed/common";
import {importProviders} from "@tsed/components-scan";
import {PlatformExpress} from "@tsed/platform-express";
import {Server} from "./Server";

async function bootstrap() {
  try {
    const scannedProviders = await importProviders({
       mount: {
           "/rest": ["**/controllers/**/*.ts"]
       },
      imports: ["**/services/**/*.ts", "**/protocols/**/*.ts"]
    });

    const platform = await PlatformExpress.bootstrap(Server, {
      ...scannedProviders
    });

    await platform.listen();

    process.on("SIGINT", () => {
      platform.stop();
    });
  } catch (error) {
    $log.error({event: "SERVER_BOOTSTRAP_ERROR", error});
  }
}

bootstrap();
```

## Why Ts.ED Engines ?

Consolidate is a really good wrapper to support multiples engines but It doesn't provide API to adding new Engines.
Ts.ED Engines provide decorator to implement custom engine:

```typescript
import {Engine, ViewEngine} from "@tsed/engines";

@ViewEngine("pug", {
  requires: ["pug", "then-pug"] // multiple require is possible. Ts.ED will use the first module resolved from node_modules
})
export class PugEngine extends Engine {
  protected $compile(template: string, options: any) {
    return this.engine.compile(template, options);
  }

  protected async $compileFile(file: string, options: any) {
    return this.engine.compileFile(file, options);
  }
}
```

By this way, you'll able to use it with Ts.ED (server or CLI) to compile and render your template.

For example, Ts.ED engines support Vite as View engine!! [See more here](tsedio/tsed-example-vite).

Ts.ED engines is already integrated to v6. You can now switch your project to this library and open issues if you have any problems.

## Why OS2 support ?

V6 is a transition from OS2 to OS3. Maintain twice spec version is very complicated. Now the implementation of OS3 in v6 is mature. OS3 offer more features that isn't possible to use it in OS2, this is why some decorators to describe spec cannot be used with OS2.

The v7 will drop the OS2 support and will be focused in future to implement more OS3 features!

I encourage you to switch you project to OS3 as soon possible ;)

### Update 2022/03/03

The OS2 won't be removed. We will use an open-source plugin to generate the OS2 spec from OS3. The advantage here, his to maintain the code base with OS3 only and keep the OS2 support!

## Why changing invoke method to async (removed)

~Actually, the InjectorService.invoke isn't able to inject async dependency to another one correctly but the feature exists with async Factory. To allow that, the DI build allow async factory before all services/provider. This mechanism works if the async factory doesn't depend on another async factory. If your async factory depend on another async, the DI won't be able to inject a resolved promise, so you will have to do the following:~

```typescript
registerProvider({
  provide: 'async_provider_1',
  async useAsyncFactory(): Promise<unknown> {
    return {};
  }
});

registerProvider({
  provide: 'async_provider_2',
  deps: ['async_provider_1'],
  async useAsyncFactory(asyncProvider1: Promise<unknown>): Promise<unknown> {
    const dep = await asyncProvider1 // add await here

    return {};
  }
});
```
> See #1502 to have more details

~To simplify the DI and fix our previous example, all providers will be considered as async provider. All providers (async and sync) will be resolved at the same times by the DI.~

v6: 
```
const service = injector.invoke(TokenService)
```

v7: 
```
const service = await injector.invoke(TokenService)
```

~In most case, you don't use injector.invoke in you code. But if it's the case, add await before `injector.invoke` to prepare your code for this breaking change!~

**Comment by Romakita** [comment]
Released :D
