### ISSUE TITLE
[v7] Remove dependencies from @tsed/common

### ISSUE THREAD

**Issue by Romakita** [TypedProject/ts-express-decorators#1755]
## Information

 Ts.ED is able to lazyload module, so now some dependencies can be removed from the `@tsed/common` package.
This option allow develop to choose which features he want use in his project, just by importing the module in the `Server.ts`.

```diff
export * from "@tsed/platform-params";
- export * from "@tsed/platform-exceptions";
- export * from "@tsed/platform-response-filter";
- export * from "@tsed/platform-cache";
export * from "@tsed/platform-middlewares";
- export * from "@tsed/components-scan";
- export * from "@tsed/platform-log-middleware";
```
Removing exports in index.ts, will causing a breaking change for the actual consumers.

## Tasks

- [ ] Lazy load the PlatformResponseFilter (https://github.com/tsedio/tsed/blob/production/packages/platform/common/src/services/PlatformHandler.ts#L34)

## Acceptance criteria

- [ ] Breaking change are documented. 
- [ ] The CLI for v6 generate a project compliant with the v7
- [ ] The v6 documentation is up to date
- [ ] The v7 documention is up to date
- [ ] The code don't import directly the concerned module and use the lazyloading feature.
