### ISSUE TITLE
[WEBSITE] Migrate the documentation on Astro

### ISSUE THREAD

**Issue by Romakita** [TypedProject/ts-express-decorators#2454]
### Is your feature request related to a problem? Please describe.

Vuepress is quite long to build documentation, and there are many bugs with the tool (nav, algolia integration, etc...).

### Describe the solution you'd like

Astro.build seems to be a good candidate to build a static website based on Markdown.

The tool provide a migration guide to migrate Vuepress site to Astro:
https://docs.astro.build/en/guides/migrate-to-astro/from-vuepress/

### Tasks

- [ ] POC:
   - [ ] The astro POC need to be compatible with existing Markdown files written here: https://github.com/tsedio/tsed/tree/production/docs
   - [ ] The astro POC should be able to be deployed on Github pages or Vercel (I would like to test the preview collaborative Vercel feature)
- [ ] Project
  - [ ] Create a monorepo with at least components & website packages
  - [ ] Install vitest to write unit test
  - [ ] Install cypress to test page and/or components
### Acceptance criteria

- [ ] The website reuse the existing docs written in markdown
- [ ] The website use designed components and components are unit tested

**Comment by Romakita** [comment]
Finally we'll migrate the documentation on VitePress.
